app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(EMAIL = "admin")
app$setInputs(PW = "admin")
app$setInputs(login = "click")

app$setInputs(action2 = "click")
app$setInputs(AddDB = "click")
app$setInputs(AddUsers = "click")
app$setInputs(BackAuthen = "click")
app$setInputs(Change = "click")
app$setInputs(ChangePW = "click")
app$setInputs(application="Authentification")
app$setInputs(ChromRadio="None")
app$setInputs(COUNTRY_NU="France")
app$setInputs(EMAIL="admin")
app$setInputs(EMAIL_ADMIN="")
app$setInputs(EMAIL_CPW="")
app$setInputs(EMAIL_NU="")
app$uploadFile(fileCDS="/srv/shiny-server/Data/cds.txt")
app$uploadFile(fileCO="/srv/shiny-server/Data/SUBCO.txt")
app$uploadFile(fileIP="/srv/shiny-server/Data/SUBIP.txt")
app$setInputs(FN_NU="")
app$setInputs(folderName="bPeaks_Results")
app$uploadFile(GFF="/srv/shiny-server/Data/Scerevisiae.gff.gz")
app$setInputs(goToAnalyzer="click")
app$setInputs(goToExplorer="click")
app$setInputs(graphicalTF="TRUE")
app$setInputs(graphicalType="pdf")
app$setInputs(header_CDS="TRUE")
app$setInputs(header_CO="TRUE")
app$setInputs(header_IP="TRUE")
app$uploadFile(InputZip="/srv/shiny-server/Data/Example.zip")
app$setInputs(LN_NU="")
app$setInputs(login="click")
app$setInputs(max=NULL)
app$setInputs(min=NULL)
app$setInputs(numAq=0.9)
app$setInputs(numCOcoeff=2)
app$setInputs(numIPcoeff=2)
app$setInputs(numLog2FC=2)
app$setInputs(numWo=50)
app$setInputs(numWs=150)
app$setInputs(peakDrawing="TRUE")
app$setInputs(promSize=800)
app$setInputs(PW="admin")
app$setInputs(PW_ADMIN="")
app$setInputs(PW_new="")
app$setInputs(PW_old="")
app$setInputs(quote_CDS="")
app$setInputs(quote_CO="")
app$setInputs(quote_IP="")
app$setInputs(resultName="bPeaks")
app$setInputs(RUN= "click")
app$setInputs(sep_CDS="\t")
app$setInputs(sep_CO="\t")
app$setInputs(sep_IP="\t")
app$setInputs(SignUp="click")
app$setInputs(smoothingValue=20)
app$setInputs(TEMP_PW="")
app$setInputs(USERNAME_NU="")
app$setInputs(UserType="Admin")
app$setInputs(withoutOverlap="TRUE")

app$snapshot()
